name: 【电费推送】
on: 
  schedule:
          - cron:  '50 3 * * *'
             # 中午12点左右推送，因为存在延时
  watch:
    types: started    #手动star执行
   
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1.4"
        
    - uses: leafo/gh-actions-luarocks@v4
    - name: 安装模块 
      run: |
             luarocks install luasocket
              luarocks install dkjson
               luarocks install luafilesystem
               luarocks install environ
        
    - name: 运行
      run: |
             lua ./gdlgxy_elc.luac
      env:
            token: ${{ secrets.token }}
            room: ${{ secrets.room }}
            url1: ${{ secrets.url1}}
            TZ: Asia/Shanghai
